### ISSUE TITLE
Switch nginx configs for Netlify domains for all apps

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/labs-infrastructure#77]
Switch NGINX configs on Labs-01 droplet for Netlify domains for all our apps. Use netlify.app instead of netlify.com.

Checklist:
- [x] production .gov
- [x] staging
- [x] all planninglabs.nyc

Make sure that all SSL certs are set up properly with the new .app domains.
Make sure nothing is statically pointing to netlify.com.

How can we make sure nothing breaks?
- Check check.ly

**Comment by rtblair** [comment]
Here's a set of search results for "netlify.com" within our repos: https://github.com/search?l=&p=1&q=netlify.com+user%3Anycplanning&ref=advsearch&type=Code

**Comment by bfreeds** [comment]
Started by updating the nginx rules for [migration.planning.nyc.gov](https://migration.planning.nyc.gov/#age) to use `netlify.app` instead of `netlify.com`. 

1.  SSH into nginx server
1.  Use VIM to change `*.netlify.com` => `*.netlify.app`
1.  Visit `migration.planning.nyc.gov`, viewing the network inspector (and disabling cache to make sure we're hitting the newly updated nginx confi)
![image](https://user-images.githubusercontent.com/5316367/79009706-294f5b00-7b2e-11ea-8e88-877ca7b4f457.png)
1.  Confirm that https is working -- certificate is still valid, which means that we don't have to regenerate certificates with certbot when we make these changes.

**Comment by bfreeds** [comment]
1.  Find all instances of "netlify.com" in our nginx configuration
    ```sh
    grep -rnw '/etc/nginx' -e 'netlify.com'
    ```
    ![image](https://user-images.githubusercontent.com/5316367/79012025-56ead300-7b33-11ea-8cb6-7b7e52263388.png)

1.  Replace all "netlify.com" instances to "netlify.app". 
    ```sh
    # from /etc/nginx/conf.d
    sudo sed -i -- 's/netlify.com/netlify.app/g' *
    ```
    [Reference stack exchange](https://unix.stackexchange.com/questions/112023/how-can-i-replace-a-string-in-a-files/112024#112024)
1.   Test results by visiting URLs of domains and confirming nothing broke
    - Ex. Zola working and certificate still valid:
    ![image](https://user-images.githubusercontent.com/5316367/79017370-2315aa80-7b3f-11ea-8459-33a489817bfa.png)

1.   Check to confirm there's no references to "netlify.com" anymore
    ```
    grep -rnw '/etc/nginx' -e 'netlify.com'
    ```
1. Check for references of "netlify.app"
    ```sh
        grep -rnw '/etc/nginx' -e 'netlify.app'
    ```
    ![image](https://user-images.githubusercontent.com/5316367/79013084-e5605400-7b35-11ea-9a7b-2595939ec0bf.png)
